import type { Workspace } from "./types";

export const workspacesLoadChunk = 10;

export const initialWorkspaces: Workspace[] = [
  { id: "northstar", name: "Northstar Analytics", pinned: true },
  { id: "customer-data", name: "Customer Data Hub", pinned: true },
  { id: "data-governance", name: "Data Governance", pinned: true },
  { id: "product-lab", name: "Product Lab", pinned: false },
  { id: "operations", name: "Operations", pinned: false },
  { id: "finance-modernization", name: "Finance Modernization", pinned: false },
  { id: "marketing-intelligence", name: "Marketing Intelligence", pinned: false },
  { id: "supply-chain", name: "Supply Chain", pinned: false },
  { id: "risk-compliance", name: "Risk & Compliance", pinned: false },
  { id: "revenue-operations", name: "Revenue Operations", pinned: false },
  { id: "research-sandbox", name: "Research Sandbox", pinned: false },
  { id: "partner-integrations", name: "Partner Integrations", pinned: false },
  { id: "platform-foundation", name: "Platform Foundation", pinned: false },
  { id: "customer-success", name: "Customer Success", pinned: false },
  { id: "data-platform", name: "Data Platform", pinned: false },
  { id: "enterprise-architecture", name: "Enterprise Architecture", pinned: false },
  { id: "identity-access", name: "Identity & Access", pinned: false },
  { id: "people-analytics", name: "People Analytics", pinned: false },
  { id: "product-analytics", name: "Product Analytics", pinned: false },
  { id: "cloud-migration", name: "Cloud Migration", pinned: false },
  { id: "quality-engineering", name: "Quality Engineering", pinned: false },
  { id: "business-operations", name: "Business Operations", pinned: false },
  { id: "fraud-detection", name: "Fraud Detection", pinned: false },
  { id: "digital-commerce", name: "Digital Commerce", pinned: false },
  { id: "customer-360", name: "Customer 360", pinned: false },
  { id: "lakehouse-modernization", name: "Lakehouse Modernization", pinned: false },
  { id: "observability", name: "Data Observability", pinned: false },
  { id: "developer-experience", name: "Developer Experience", pinned: false },
  { id: "regional-expansion", name: "Regional Expansion", pinned: false },
  { id: "sales-forecasting", name: "Sales Forecasting", pinned: false },
  { id: "service-operations", name: "Service Operations", pinned: false },
  { id: "security-labs", name: "Security Labs", pinned: false },
  { id: "analytics-enablement", name: "Analytics Enablement", pinned: false },
  { id: "vendor-management", name: "Vendor Management", pinned: false },
  { id: "data-contracts", name: "Data Contracts", pinned: false },
  { id: "growth-experiments", name: "Growth Experiments", pinned: false },
  { id: "executive-insights", name: "Executive Insights", pinned: false },
];
